<?php
header("Content-Type:application/json");

include_once 'coffeescript-php/src/CoffeeScript/Init.php';

CoffeeScript\Init::load();

function create_or_update_file($code){
	// make this dynamic with a slug.css as the file name, replacing "slug" the actual slug passed in through the GET url parameter
	if(file_exists("./1WbCQ.js")){
		file_put_contents('1WbCQ.js', $code);
	}else{
		$my_file = '1WbCQ.js';
		$handle = fopen($my_file, 'w');
		fwrite($handle, $code);
		fclose($handle);
	}
}

## To avoid no code error for coffeescript put a comment at the top of the file that says this exactly "/* Made with Fiddles for iOS */" ##
			
try{
	
	// See available options above.
	$file = file_get_contents("./1WbCQ.coffee", FILE_USE_INCLUDE_PATH);
	
	$js = CoffeeScript\Compiler::compile($file, []);
	
	$return = trim(str_ireplace("// Generated by CoffeeScript PHP 1.3.1\n", "", $js));
	
	create_or_update_file($return);
	
	echo json_encode(["code" => 200,"msg" => $return]);
}catch (Exception $e){
	$errMsg = $e->getMessage();
	$message = ucfirst(str_replace("In , ", "", $errMsg));
	
	echo json_encode(["err" => ["code" => 507,"msg" => $message]]);
}
